swagger: "2.0"
info:
  title: backend-gateway Backend para clientes
  description: "Get the clients info"
  version: "1.0.0"
schemes:
  - "https"
paths:
  "/customers/ping":
    get:
      description: "Get the health status of the api"
      operationId: "ping"
      x-google-backend:
        address: https://backend-customers-143596276526.us-central1.run.app/customers/ping
      responses:
        200:
          description: "Success."
        500:
          description: "Error"